# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GenerationConfiguration(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GenerationConfiguration()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGenerationConfiguration(cls, buf, offset=0):
        """Deprecated, please use GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # GenerationConfiguration
    def Init(self, buf, pos):
        self._tab = flatbuffers.Table(buf, pos)

    # GenerationConfiguration
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # GenerationConfiguration
    def StartWidth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # GenerationConfiguration
    def StartHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # GenerationConfiguration
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # GenerationConfiguration
    def Steps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # GenerationConfiguration
    def GuidanceScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GenerationConfiguration
    def Strength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GenerationConfiguration
    def Model(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GenerationConfiguration
    def Sampler(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # GenerationConfiguration
    def BatchCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1

    # GenerationConfiguration
    def BatchSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1


def GenerationConfigurationStart(builder):
    builder.StartObject(84)  # Total number of fields in schema

def Start(builder):
    GenerationConfigurationStart(builder)

def GenerationConfigurationAddId(builder, id):
    builder.PrependInt64Slot(0, id, 0)

def AddId(builder, id):
    GenerationConfigurationAddId(builder, id)

def GenerationConfigurationAddStartWidth(builder, startWidth):
    builder.PrependUint16Slot(1, startWidth, 0)

def AddStartWidth(builder, startWidth):
    GenerationConfigurationAddStartWidth(builder, startWidth)

def GenerationConfigurationAddStartHeight(builder, startHeight):
    builder.PrependUint16Slot(2, startHeight, 0)

def AddStartHeight(builder, startHeight):
    GenerationConfigurationAddStartHeight(builder, startHeight)

def GenerationConfigurationAddSeed(builder, seed):
    builder.PrependUint32Slot(3, seed, 0)

def AddSeed(builder, seed):
    GenerationConfigurationAddSeed(builder, seed)

def GenerationConfigurationAddSteps(builder, steps):
    builder.PrependUint32Slot(4, steps, 0)

def AddSteps(builder, steps):
    GenerationConfigurationAddSteps(builder, steps)

def GenerationConfigurationAddGuidanceScale(builder, guidanceScale):
    builder.PrependFloat32Slot(5, guidanceScale, 0.0)

def AddGuidanceScale(builder, guidanceScale):
    GenerationConfigurationAddGuidanceScale(builder, guidanceScale)

def GenerationConfigurationAddStrength(builder, strength):
    builder.PrependFloat32Slot(6, strength, 0.0)

def AddStrength(builder, strength):
    GenerationConfigurationAddStrength(builder, strength)

def GenerationConfigurationAddModel(builder, model):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(model), 0)

def AddModel(builder, model):
    GenerationConfigurationAddModel(builder, model)

def GenerationConfigurationAddSampler(builder, sampler):
    builder.PrependUint8Slot(8, sampler, 0)

def AddSampler(builder, sampler):
    GenerationConfigurationAddSampler(builder, sampler)

def GenerationConfigurationAddBatchCount(builder, batchCount):
    builder.PrependUint32Slot(9, batchCount, 1)

def AddBatchCount(builder, batchCount):
    GenerationConfigurationAddBatchCount(builder, batchCount)

def GenerationConfigurationAddBatchSize(builder, batchSize):
    builder.PrependUint32Slot(10, batchSize, 1)

def AddBatchSize(builder, batchSize):
    GenerationConfigurationAddBatchSize(builder, batchSize)

def GenerationConfigurationEnd(builder):
    return builder.EndObject()

def End(builder):
    return GenerationConfigurationEnd(builder)

# Additional fields matching exact schema order
def GenerationConfigurationAddHiresFix(builder, hiresFix):
    builder.PrependBoolSlot(11, hiresFix, 0)

def AddHiresFix(builder, hiresFix):
    GenerationConfigurationAddHiresFix(builder, hiresFix)

# Manually added hires fix parameters (not in auto-generated code)
def GenerationConfigurationAddHiresFixStartWidth(builder, hiresFixStartWidth):
    builder.PrependUint16Slot(12, hiresFixStartWidth, 0)

def AddHiresFixStartWidth(builder, hiresFixStartWidth):
    GenerationConfigurationAddHiresFixStartWidth(builder, hiresFixStartWidth)

def GenerationConfigurationAddHiresFixStartHeight(builder, hiresFixStartHeight):
    builder.PrependUint16Slot(13, hiresFixStartHeight, 0)

def AddHiresFixStartHeight(builder, hiresFixStartHeight):
    GenerationConfigurationAddHiresFixStartHeight(builder, hiresFixStartHeight)

def GenerationConfigurationAddHiresFixStrength(builder, hiresFixStrength):
    builder.PrependFloat32Slot(14, hiresFixStrength, 0.0)

def AddHiresFixStrength(builder, hiresFixStrength):
    GenerationConfigurationAddHiresFixStrength(builder, hiresFixStrength)

def GenerationConfigurationAddUpscaler(builder, upscaler):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(upscaler), 0)

def AddUpscaler(builder, upscaler):
    GenerationConfigurationAddUpscaler(builder, upscaler)

def GenerationConfigurationAddSeedMode(builder, seedMode):
    builder.PrependUint8Slot(17, seedMode, 0)

def AddSeedMode(builder, seedMode):
    GenerationConfigurationAddSeedMode(builder, seedMode)

def GenerationConfigurationAddClipSkip(builder, clipSkip):
    builder.PrependUint32Slot(18, clipSkip, 1)

def AddClipSkip(builder, clipSkip):
    GenerationConfigurationAddClipSkip(builder, clipSkip)

def GenerationConfigurationStartControlsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartControlsVector(builder, numElems):
    return GenerationConfigurationStartControlsVector(builder, numElems)

def GenerationConfigurationAddControls(builder, controls):
    builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(controls), 0)

def AddControls(builder, controls):
    GenerationConfigurationAddControls(builder, controls)

def GenerationConfigurationStartLorasVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLorasVector(builder, numElems):
    return GenerationConfigurationStartLorasVector(builder, numElems)

def GenerationConfigurationAddLoras(builder, loras):
    builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(loras), 0)

def AddLoras(builder, loras):
    GenerationConfigurationAddLoras(builder, loras)

def GenerationConfigurationAddMaskBlur(builder, maskBlur):
    builder.PrependFloat32Slot(21, maskBlur, 0.0)

def AddMaskBlur(builder, maskBlur):
    GenerationConfigurationAddMaskBlur(builder, maskBlur)

def GenerationConfigurationAddFaceRestoration(builder, faceRestoration):
    builder.PrependUOffsetTRelativeSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(faceRestoration), 0)

def AddFaceRestoration(builder, faceRestoration):
    GenerationConfigurationAddFaceRestoration(builder, faceRestoration)

def GenerationConfigurationAddRefinerModel(builder, refinerModel):
    builder.PrependUOffsetTRelativeSlot(28, flatbuffers.number_types.UOffsetTFlags.py_type(refinerModel), 0)

def AddRefinerModel(builder, refinerModel):
    GenerationConfigurationAddRefinerModel(builder, refinerModel)

def GenerationConfigurationAddOriginalImageWidth(builder, originalImageWidth):
    builder.PrependUint32Slot(29, originalImageWidth, 0)

def AddOriginalImageWidth(builder, originalImageWidth):
    GenerationConfigurationAddOriginalImageWidth(builder, originalImageWidth)

def GenerationConfigurationAddOriginalImageHeight(builder, originalImageHeight):
    builder.PrependUint32Slot(30, originalImageHeight, 0)

def AddOriginalImageHeight(builder, originalImageHeight):
    GenerationConfigurationAddOriginalImageHeight(builder, originalImageHeight)

def GenerationConfigurationAddTargetImageWidth(builder, targetImageWidth):
    builder.PrependUint32Slot(33, targetImageWidth, 0)

def AddTargetImageWidth(builder, targetImageWidth):
    GenerationConfigurationAddTargetImageWidth(builder, targetImageWidth)

def GenerationConfigurationAddTargetImageHeight(builder, targetImageHeight):
    builder.PrependUint32Slot(34, targetImageHeight, 0)

def AddTargetImageHeight(builder, targetImageHeight):
    GenerationConfigurationAddTargetImageHeight(builder, targetImageHeight)

def GenerationConfigurationAddMaskBlurOutset(builder, maskBlurOutset):
    builder.PrependInt32Slot(47, maskBlurOutset, 0)

def AddMaskBlurOutset(builder, maskBlurOutset):
    GenerationConfigurationAddMaskBlurOutset(builder, maskBlurOutset)

def GenerationConfigurationAddSharpness(builder, sharpness):
    builder.PrependFloat32Slot(48, sharpness, 0.0)

def AddSharpness(builder, sharpness):
    GenerationConfigurationAddSharpness(builder, sharpness)

def GenerationConfigurationAddShift(builder, shift):
    builder.PrependFloat32Slot(49, shift, 1.0)

def AddShift(builder, shift):
    GenerationConfigurationAddShift(builder, shift)

def GenerationConfigurationAddTiledDecoding(builder, tiledDecoding):
    builder.PrependBoolSlot(53, tiledDecoding, 0)

def AddTiledDecoding(builder, tiledDecoding):
    GenerationConfigurationAddTiledDecoding(builder, tiledDecoding)

def GenerationConfigurationAddPreserveOriginalAfterInpaint(builder, preserveOriginalAfterInpaint):
    builder.PrependBoolSlot(58, preserveOriginalAfterInpaint, 1)

def AddPreserveOriginalAfterInpaint(builder, preserveOriginalAfterInpaint):
    GenerationConfigurationAddPreserveOriginalAfterInpaint(builder, preserveOriginalAfterInpaint)

def GenerationConfigurationAddTiledDiffusion(builder, tiledDiffusion):
    builder.PrependBoolSlot(59, tiledDiffusion, 0)

def AddTiledDiffusion(builder, tiledDiffusion):
    GenerationConfigurationAddTiledDiffusion(builder, tiledDiffusion)

def GenerationConfigurationAddCausalInferencePad(builder, causalInferencePad):
    builder.PrependInt32Slot(81, causalInferencePad, 0)

def AddCausalInferencePad(builder, causalInferencePad):
    GenerationConfigurationAddCausalInferencePad(builder, causalInferencePad)

def GenerationConfigurationAddCfgZeroStar(builder, cfgZeroStar):
    builder.PrependBoolSlot(82, cfgZeroStar, 0)

def AddCfgZeroStar(builder, cfgZeroStar):
    GenerationConfigurationAddCfgZeroStar(builder, cfgZeroStar)

def GenerationConfigurationAddCfgZeroInitSteps(builder, cfgZeroInitSteps):
    builder.PrependInt32Slot(83, cfgZeroInitSteps, 0)

def AddCfgZeroInitSteps(builder, cfgZeroInitSteps):
    GenerationConfigurationAddCfgZeroInitSteps(builder, cfgZeroInitSteps)
